### ISSUE TITLE
Opencv 3.2.0 errors

### ISSUE THREAD

**Issue by mnaranjo** [iacopomasi/face_specific_augm#3]
Hi,

I'm testing the project and I have some problems. 
1) I have changed ThreeD_Model.py:63 --> _**contours, hierarchy =**_ to _**\_, contours, hierarchy =**_
Because with opencv 3.2.0 findCountours return 3 params.

2) Now I can run the demo.py script, but when I have generated 10 images in output (always 10 images), I get this error:
```
OpenCV Error: Assertion failed (dst.cols < SHRT_MAX && dst.rows < SHRT_MAX && src.cols < SHRT_MAX && src.rows < SHRT_MAX) in remap, file <PATH_TO_OPENCV>/opencv-3.2.0/modules/imgproc/src/imgwarp.cpp, line 4956
Traceback (most recent call last):
  File "demo.py", line 111, in <module>
    demo()
  File "demo.py", line 86, in demo
    model3D.ref_U, eyemask, model3D.facemask, opts)
  File "<PATH_TO_FACESPECIFICAUGM>/faceSpecificAugm/renderer.py", line 109, in render
    frontal_raw = warpImg(img, ref_U.shape[0], ref_U.shape[1], prj_jnt, ind_jnt)
  File "<PATH_TO_FACESPECIFICAUGM>/faceSpecificAugm/renderer.py", line 25, in warpImg
    np.squeeze( np.asarray( prj[1,:] ) ).astype('float32'),  cv2.INTER_CUBIC)
cv2.error: <PATH_TO_OPENCV>/opencv-3.2.0/modules/imgproc/src/imgwarp.cpp:4956: error: (-215) dst.cols < SHRT_MAX && dst.rows < SHRT_MAX && src.cols < SHRT_MAX && src.rows < SHRT_MAX in function remap
```

Any ideas? Thanks!!!

**Comment by beeva-enriqueotero** [comment]
I get the same error, even for a single image. I'm using opencv-python==3.2.0.6

**Comment by beeva-enriqueotero** [comment]
It works fine with version 3.1.0.5

**Comment by zhixuanli** [comment]
Hi every one, I'm a student from China.
Here's the blog of the whole process from install opencv to run the imput1 example
May be can help you a little

http://www.cnblogs.com/QingHuan/p/6753440.html

**Comment by iacopomasi** [comment]
Hi @zhixuanli ,
thank you very much for your help and I am sure your guide can help the community so much.

Thanks,
-iacopo

**Comment by dshahrokhian** [comment]
I just spent the entire night trying to fix this. Just wanted to share the solution that ended up working for me: 

1. The line throwing the error is an assertion. Comment the line throwing the error: 
`<opencv folder>/modules/imgproc/src/imgwarp.cpp:4956: error: (-215) dst.cols < SHRT_MAX && dst.rows < SHRT_MAX && src.cols < SHRT_MAX && src.rows < SHRT_MAX in function remap`
2. Recompile OpenCV (cmake, make)
3. Install it again (make install)

**Comment by iacopomasi** [comment]
Hi All,
thank you for your feedback. I also got into trouble while running this with OpenCV3.

I think there is a quick fix that I used that briefly was the following:

- check which version of Opencv is running inside the code with something similar to `python -c 'import cv2; print cv2.__version__'`
- use the detected version to redirect the code to use OpenCV2 function in one case (the current code) or the new modified code to run smoothly with OpenCV3

I think I did this patch locally and it worked but I did not have the time to push it on the server.
So in theory there is not need to modify and recompile OpenCV3.

I will try to push the patch in case I have time.

I hope this helps,
iacopo

**Comment by benibraz** [comment]
Hi,
I'm having the same issue here using OpenCV 3.2.0.
Is there any other solution except the one dshahrokhian posted? I couldn't find the imgwarp.cpp file. 

Many thanks,
-Benny.

**Comment by WajWaraich** [comment]
I've also got this issue, I've tried hacking around the problem with no success, it looks like the current solution is really just to recompile. I'm sorry that this comment does not offer any solutions but just wanted to highlight that this is not an isolated incident.

Kind regards,
Waj

**Comment by dshahrokhian** [comment]
@benibraz it's at `<opencv folder>/modules/imgproc/src/imgwarp.cpp`.

@WajWaraich Did you try my solution?

Dani

**Comment by WajWaraich** [comment]
@dshahrokhian 

Dani, thanks for your reply, I was trying to avoid having to recompile the library but I might have to now. I was planning on compiling OpenCV 3.3 and seeing whether that still contained the bug. 

**UPDATE 1:** Upgrading to 3.3 did not help, the error simply went from line 4956 to 4944 as there have been some changes in `imgwarp.cpp`, I'll try commenting out the `CV_Assert()` line and recompile the library - see if that helps.

**UPDATE 2:** Got it all working by following Dani's ( @dshahrokhian ) instructions, just commented out the line that was causing the issue and recompiled and everything seems to be working smoothly.

**Comment by andychuajl** [comment]
The work around for OpenCV 3.2 is to edit renderer.py `def wrapImg()` 
`if prj.size != 0:`
`pixels = cv2.remap(img, np.squeeze( np.asarray( prj[0,:] ) ).astype('float32').reshape(t_height, t_width),\`
`np.squeeze( np.asarray( prj[1,:] ) ).astype('float32').reshape(t_height, t_width),  cv2.INTER_CUBIC)`
`pixels = pixels.reshape(pixels.shape[0]*pixels.shape[1], pixels.shape[2])`
`#        pixels = pixels[:,0,:]`
`new_img[idx,:] = pixels`

**Comment by abhi-infrrd** [comment]
@andychuajl  where is this file?

**Comment by iacopomasi** [comment]
I think the file you need is in `renderer.py`

**Comment by XinyingZheng** [comment]
> Hi every one, I'm a student from China.
> Here's the blog of the whole process from install opencv to run the imput1 example
> May be can help you a little
> 
> http://www.cnblogs.com/QingHuan/p/6753440.html



> Hi,
> 
> I'm testing the project and I have some problems.
> 
> 1. I have changed ThreeD_Model.py:63 --> _**contours, hierarchy =**_ to _**_, contours, hierarchy =**_
>    Because with opencv 3.2.0 findCountours return 3 params.
> 2. Now I can run the demo.py script, but when I have generated 10 images in output (always 10 images), I get this error:
> 
> ```
> OpenCV Error: Assertion failed (dst.cols < SHRT_MAX && dst.rows < SHRT_MAX && src.cols < SHRT_MAX && src.rows < SHRT_MAX) in remap, file <PATH_TO_OPENCV>/opencv-3.2.0/modules/imgproc/src/imgwarp.cpp, line 4956
> Traceback (most recent call last):
>   File "demo.py", line 111, in <module>
>     demo()
>   File "demo.py", line 86, in demo
>     model3D.ref_U, eyemask, model3D.facemask, opts)
>   File "<PATH_TO_FACESPECIFICAUGM>/faceSpecificAugm/renderer.py", line 109, in render
>     frontal_raw = warpImg(img, ref_U.shape[0], ref_U.shape[1], prj_jnt, ind_jnt)
>   File "<PATH_TO_FACESPECIFICAUGM>/faceSpecificAugm/renderer.py", line 25, in warpImg
>     np.squeeze( np.asarray( prj[1,:] ) ).astype('float32'),  cv2.INTER_CUBIC)
> cv2.error: <PATH_TO_OPENCV>/opencv-3.2.0/modules/imgproc/src/imgwarp.cpp:4956: error: (-215) dst.cols < SHRT_MAX && dst.rows < SHRT_MAX && src.cols < SHRT_MAX && src.rows < SHRT_MAX in function remap
> ```
> 
> Any ideas? Thanks!!!

so,how you solve this question finally?

**Comment by XinyingZheng** [comment]
> I just spent the entire night trying to fix this. Just wanted to share the solution that ended up working for me:
> 
> 1. The line throwing the error is an assertion. Comment the line throwing the error:
>    `<opencv folder>/modules/imgproc/src/imgwarp.cpp:4956: error: (-215) dst.cols < SHRT_MAX && dst.rows < SHRT_MAX && src.cols < SHRT_MAX && src.rows < SHRT_MAX in function remap`
> 2. Recompile OpenCV (cmake, make)
> 3. Install it again (make install)

how to recompile opencv?

**Comment by secretdragon** [comment]
> It works fine with version 3.1.0.5

**Comment by secretdragon** [comment]
> It works fine with version 3.1.0.5

me too
